In [1]:
pip install numpy


In [2]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [6]:
# 1. Create a 1D array of numbers 0-9

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# 2. Create a 3x3 array of all 7s

a = np.full((3,3), 7)
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [15]:
# 3. Create a 2x3x4 array of zeros, print its shape

a = np.zeros((2,3,4))
print(a.shape)

(2, 3, 4)


In [16]:
# 4. Create an array of 20 numbers, reshape into (4,5), then flatten back to 1D

a = np.arange(20)
b = a.reshape(4,5)
c = b.reshape(-1)
print(b)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
# 5. From a 1D array of 10 numbers, extract elements at index 2,4,6

a = np.arange(10)
print(a[[2,4,6]])

[2 4 6]


In [18]:
# 6. From a 4x4 array, extract the middle 2x2 block

a = np.arange(16).reshape(4,4)
middle = a[1:3, 1:3]
print(middle)

[[ 5  6]
 [ 9 10]]


In [19]:
# 7. Given an array of ages, extract all ages >= 18 using masking

ages = np.array([15, 22, 17, 30, 12, 19])
adults = ages[ages >= 18]
print(adults)

[22 30 19]


In [20]:
# 8. Add a (4,1) array to a (1,4) array, print the result and its shape

a = np.array([[1],[2],[3],[4]])
b = np.array([[10,20,30,40]])
result = a + b
print(result)
print(result.shape)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]
 [14 24 34 44]]
(4, 4)


In [21]:
# 9. Given a (3,3) matrix, subtract the row-wise mean from each row

m = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_means = m.mean(axis=1, keepdims=True)
result = m - row_means
print(row_means)
print(result)

[[2.]
 [5.]
 [8.]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [22]:
# 10. Compare loop vs vectorized: square 500,000 numbers both ways, print both timings

import time
n = 500_000
lst = list(range(n))
arr = np.arange(n)

start = time.time()
sq_loop = [x**2 for x in lst]
t_loop = time.time() - start

start = time.time()
sq_vec = arr**2
t_vec = time.time() - start

print("Loop:", t_loop)
print("Vectorized:", t_vec)

Loop: 0.04166555404663086
Vectorized: 0.0030219554901123047
