In [1]:
# 1. Matrix multiplication (2x2)

import numpy as np
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print(A @ B)

[[19 22]
 [43 50]]


In [3]:
# 2. Matrix multiplication (3x3)

A3 = np.array([[1,0,2],
               [0,1,1],
               [2,1,0]])
B3 = np.array([[1,2,0],
               [0,1,1],
               [1,0,1]])
print(A3 @ B3)

[[3 2 2]
 [1 1 2]
 [2 5 1]]


In [4]:
# 3. Determinant (2x2)
# Measures how much a matrix scales area. det=0 means it collapses space (no inverse).

A = np.array([[1, 2],
              [3, 4]])
print(np.linalg.det(A)) 
 

-2.0000000000000004


In [5]:
# 4. Determinant (3x3)

A3 = np.array([[1,0,2],
               [0,1,1],
               [2,1,0]])
print(np.linalg.det(A3))

-5.000000000000001


In [6]:
# 5. Inverse
# A @ A_inv = Identity matrix. Only exists if det != 0.

A = np.array([[4, 7],
              [2, 6]])
A_inv = np.linalg.inv(A)
print(A_inv)
print(A @ A_inv)   # should be identity

[[ 0.6 -0.7]
 [-0.2  0.4]]
[[1. 0.]
 [0. 1.]]


In [2]:
# 6. Singular matrix (no inverse)

# det=0 means matrix has no inverse (throws error).

S = np.array([[1, 2],
              [2, 4]])
print(np.linalg.det(S))   # 0.0
try:
    np.linalg.inv(S)
except np.linalg.LinAlgError as e:
    print("Error:", e)

0.0
Error: Singular matrix
